config/routes.rb
MyWeight::Application.routes.draw do

  get "user_profile/index"

  devise_for :users

  resources :weights, :except => [:index]
  resources :users
  match "weights"  => "home#index"
  get "home/index"
  
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :weights 
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :height, :perc_fat, :gender
 
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
  
  validates :weight,    :presence => true
  validates :waist,     :presence => true
  validates :neck,      :presence => true
  validates :weight, :numericality => {:greater_than_or_equal_to => 0.01}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    @weight = Weight.new
    @weights = current_user.weights.order("date DESC")
    @last_weight = current_user.weights.find(:last)	
  end

end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  before_filter :authenticate_user!
  def index
     @user = User.new
     @user = current_user 
  end
# 
  # def edit
    # @user = current_user
  # end
# 
# 
  # def update
    # @user = current_user
# 
    # respond_to do |format|
      # if @user.update_attributes(current_user)
        # format.html { redirect_to(@user, :notice => 'Profile was successfully updated.') }
      # else
        # format.html { render :action => "edit" }
      # end
    # end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
 def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(user_profile_index_path, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  
    def update_password
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end

  

end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_filter :authenticate_user!
  def show
    @weight = Weight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @weight = Weight.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @weight = Weight.find(params[:id])
  end

  def create

    @weights = Weight.all
    @weight = Weight.new(params[:weight])
    @weight.date = Time.now
    @weight.user_id = current_user.id

    respond_to do |format|
      if @weight.save
        format.html { redirect_to(root_path, :notice => 'Weight was successfully created.') }
      else
        format.html { render :action => "home/index" }
      end
    end
  end

  def update
    @weight = Weight.find(params[:id])

    respond_to do |format|
      if @weight.update_attributes(params[:weight])
        format.html { redirect_to(root_path, :notice => 'Weight was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @weight = Weight.find(params[:id])
    @weight.destroy

    respond_to do |format|
      format.html { redirect_to(root_path, :notice => 'Weight was deleted.') }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "success"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
  
#  def calculate_fat_weight_percent(height, waist, neck)
 #   (495/((1.0324-((Math.log(waist-neck)/Math.log(10))*0.19077)) + (Math.log(height)/Math.log(10))*0.15456))-450
  #end
  
  def calculate_fat_weight_percent(height, waist, neck, hip, gender)
    if(gender == "Male")
      (495/((1.0324-((Math.log(waist-neck)/Math.log(10))*0.19077)) + (Math.log(height)/Math.log(10))*0.15456))-450
    else
      (495/((1.29579-(0.35004*(Math.log((hip+waist)-neck)/Math.log(10)))) + (Math.log(height)/Math.log(10))*0.22100))-450
    end  
  end

  def calculate_lean_weight_percent(height, waist, neck, hip, gender)
    return 100-calculate_fat_weight_percent(height, waist, neck, hip, gender)
  end
  
  def calculate_fat_weight(weight, height, waist, neck, hip, gender)
    (calculate_fat_weight_percent(height, waist, neck, hip, gender))/100 * weight
  end
      
  def calculate_lean_weight(weight, height, waist, neck, hip, gender)
    (calculate_lean_weight_percent(height, waist, neck, hip, gender))/100 * weight
  end
  
  def print_all_values(weight, height, waist, neck, perc_fat, hip)
    weight.to_s + " # " + height.to_s + " # " + waist.to_s + " # " + neck.to_s + " # " + perc_fat.to_s + " # " + hip.to_s + " # "
  end 
  
  def calculate_ideal_weight(weight, height, waist, neck, hip, perc_fat, gender)
     (weight - (calculate_fat_weight_percent(height, waist, neck, hip, gender) / 100 * weight)) / (1 - (perc_fat / 100));
  end  
  
  #"4-hour body" measure
  def calculate_total_inches(waist, hip, right_arm, left_arm, right_leg, left_leg)
    ti = 0
    if(right_arm != 0 or left_arm != 0 or right_leg != 0 or left_leg != 0)
      ti = (waist + hip + right_arm + left_arm + right_leg + left_arm)
    end
    return ti
  end   
  
end

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
						"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
	<title>MyWeight</title>
	<%= stylesheet_link_tag "myweight", :media => "all" %>
</head> 
<body id="store">
<div>
<%= render "weights/form" %>
</div>
<p>
<div class="ideal_weight">
<%= render "weights/ideal_weight" %>
</div>
<p>
<div class="graph_weight">
<%= render "weights/show" %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>MyWeight</title>
		<%= stylesheet_link_tag 'bootstrap', 'bootstrap-responsive' %>
		<%= javascript_include_tag 'jquery-1.8.3.min', 'jquery.validate', 'bootstrap','application', 'rails' %>
		<%= csrf_meta_tag %>
		<style type="text/css">
			body {
				padding-top: 60px;
				padding-bottom: 40px;
			}
			.sidebar-nav {
				padding: 9px 0;
			}
		</style>
	</head>
	<body>

		<% flash.each do |name, msg| %>

		<% if msg.is_a?(String) %>
		<div class="alert alert-<%= flash_class(name) %>">
			<button type="button" class="close" data-dismiss="alert">
				&#215;
			</button>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		</div>
		<% end %>

		<% end %>
		<% if user_signed_in? %>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container" style="width: auto; padding: 0 20px;">
					<%= link_to "My Weight", home_index_path, :class => "brand", :id => "myweight_menu_bar"%>
					<ul class="nav">
						<li id ="home_menu_bar" class ="active"><%= link_to "Home", home_index_path%></a></li>
						<ul class="nav pull-left">
							<li class="dropdown" id="profile_menu_bar">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile<b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li>
										<a href="/user_profile/index">Details</a>
									</li>
									<li class="divider"></li>
									<li>
										<%= link_to "Edit Profile", edit_user_path(current_user)%></a>
									</li>
							</li>
						</ul>
					</ul>
					</ul>
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Signed in as <%= current_user.email %><b class="caret"></b></a>

							<ul class="dropdown-menu">
								<li>
									<a href="/users/sign_out" data-method="delete" rel="nofollow"><i class="icon-off"></i><span class="icon-padding-right">Sign out</span> </a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/user_profile/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
						"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
	<title>MyWeight - User Profile</title>
	<%= stylesheet_link_tag "myweight", :media => "all" %>
</head> 
<body id="store">
<table>
  <tr>
  	<td><div class="tab_profile_header">Email</div></td>
  	<td align="left">
  		<div class="tab_profile_value"><%= @user.email %></div>
  	</td>
  </tr>
  <tr>
  	<td><div class="tab_profile_header">Height</div></td>
  	<td align="left"><div class="tab_profile_value"><%= number_with_precision(@user.height) %></div></td>
  </tr>
  <tr>
  	<td><div class="tab_profile_header">Percent Desired</div></td>
  	<td align="left"><div class="tab_profile_value"><%= number_to_percentage(@user.perc_fat, :precision => 0) %></div></td>
  </tr>
  <tr>
  	<td><div class="tab_profile_header">Gender</div></td>
  	<td align="left"><div class="tab_profile_value"><%= @user.gender %></div></td>
  </tr>
</table>
</body>
</html>
<script>
		$('#profile_menu_bar').addClass('active');
		$('#home_menu_bar').removeClass('active');
</script>

app/views/users/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
						"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
	<title>MyWeight - Edit User Profile</title>
	<%= stylesheet_link_tag "myweight", :media => "all" %>
</head> 
<body id="store">
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<table cellpadding="5" cellspacing="5">
			<tr>
				<td colspan="2" align="Center"><div class="tab_profile_header">Change User Details</div></td>
			</tr>
			<tr>
				<td><div><%= f.label :email %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :email, :size => 40, :class => "input-large" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :height %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :height, :size => 5, :class => "input-mini" %>cm</div></td>
			</tr>
			<tr>
				<td><div><%= f.label :perc_fat %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :perc_fat, :size => 5, :class => "input-mini" %>%</div></td>
			</tr>
			<tr>
				<td><div><%= f.label :gender %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.select :gender, options_for_select([["Male", "Male"], ["Female", "Female"]], @user.gender) %></div></td>
			</tr>
			<tr>
				<td align="center" colspan="2"><div class="tab_profile_value"><%= f.submit %></div></td>
			</tr>	
		</table>	
<% end %>
<br><br>
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
			<table cellpadding="5" cellspacing="5">
			<tr>
				<td colspan="2" align="Center"><div class="tab_profile_header">Change Password</div></td>
			</tr>
			<tr>
				<td>
				<div><%= f.label :password, "Password" %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.password_field :password, :autocomplete => "off" , :size => 20 %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :password_confirmation %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.password_field :password_confirmation, :size => 20 %></div></td>
			</tr>
			<tr>
				<td align="center" colspan="2"><div class="tab_profile_value"><%= f.submit "Change Password" %></div></td>
			</tr>
		</table>
<% end %>



</body>
</html>
<script>
		$('#profile_menu_bar').addClass('active');
		$('#home_menu_bar').removeClass('active');
</script>

app/views/weights/_form.html.erb
<%= form_for(@weight) do |f| %>
	<% if @weight.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>
			<ul>
			<% @weight.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<table border="0">
			<tr>
				<td><div><%= f.label :weight%></div></td>	
				<td><div><%= f.text_field :weight, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :waist %></div></td>
				<td><div><%= f.text_field :waist, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>	
				<td><div><%= f.label :neck %></div></td>	 
				<td><div><%= f.text_field :neck, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :hip %></div></td>
				<td><div><%= f.text_field :hip, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :left_arm %></div></td>
				<td><div><%= f.text_field :left_arm, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :right_arm %></div></td>
				<td><div><%= f.text_field :right_arm, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :left_leg %></div></td>
				<td><div><%= f.text_field :left_leg, :size => 5, :class => "input-mini" %></div></td>
			</tr>
			<tr>
				<td><div><%= f.label :right_leg %></div></td>
				<td><div><%= f.text_field :right_leg, :size => 5, :class => "input-mini" %></div></td>
			</tr>	
			<tr>
				<td colspan="2"><div style="clear:both; text-align: center"><%= f.submit "Save", :class => "btn btn-info" %></div></td>
			</tr>
		</table>
	</div> 
<% end %>

app/views/weights/_ideal_weight.html.erb
<table>
  <tr>
    <th align="left"><div class="tab_profile_header">Ideal Weight</div></th>
    <td align="left"><div class="tab_profile_value"><%=number_with_precision(calculate_ideal_weight(@last_weight.weight, current_user.height, @last_weight.waist, @last_weight.neck, @last_weight.hip, current_user.perc_fat, current_user.gender)) %> Kgs</div></td>
  </tr>
</table>

app/views/weights/_show.html.erb
<table class="table table-hover table-condensed">
  <tr>
    <th align="left">Weight</th>
    <th align="left"><div class="negative_label">Fat Weight</div></th>
    <th align="left"><div class="negative_label">% Fat Weight</div></th>
    <th align="left"><div class="positive_label">Lean Weight</div></th>
    <th align="left"><div>TI</div></th>
    <th align="left">Date</th>
    <th align="center">Actions</th>
  </tr>
<% @weights.each do |weight| %>
  <tr>
    <td width="65" align="left"><div><%= number_with_precision(weight.weight) %></div></td>
    <td width="90" align="left"><div><%= number_with_precision(calculate_fat_weight(weight.weight, current_user.height, weight.waist, weight.neck, weight.hip, current_user.gender)) %></div></td>
    <td width="120" align="left"><div><%= number_to_percentage((calculate_fat_weight(weight.weight, current_user.height, weight.waist, weight.neck, weight.hip, current_user.gender)/weight.weight)*100) %></div></td>
    <td width="100" align="left"><div><%= number_with_precision(calculate_lean_weight(weight.weight, current_user.height, weight.waist, weight.neck, weight.hip, current_user.gender)) %></div></td>
    <td width="65" align="left"><div><%= number_with_precision(calculate_total_inches(weight.waist, weight.hip, weight.right_arm, weight.left_arm, weight.right_leg, weight.left_leg)) %></div></td>
    <td width="150" align="left"><div><%= l weight.date, :format => :short  %></div></td>
    <td width="125" align="left"><div>
    		<%= link_to "Edit", edit_weight_path(weight), :class => "btn btn-mini"%> 
    		<%= link_to "Delete", weight, :confirm => "Are you sure?", :method => :delete , :class => "btn btn-mini"%>
    		<%= link_to 'Show', weight_path(weight) , :class => "btn btn-mini"%>
    </div></td>
  </tr>
<% end %>
</table>

app/views/weights/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
						"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
	<title>MyWeight - Edit Weight</title>
	<%= stylesheet_link_tag "myweight", :media => "all" %>
</head> 
<body id="store">
<h2>Edit Weight</h2>
<p>Go to <%= link_to "weights", home_index_path%>.</p>
<%= form_for(@weight) do |f| %>
	<% if @weight.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>
			<ul>
			<% @weight.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<table>
		<tr>
			<td><div class="tab_profile_header"><%= f.label :weight %></div></td>
			<td align="left"><div class="tab_profile_value"><%= f.text_field :weight, :size => 5 %>kgs</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header"><%= f.label :date %></div></td>
			<td align="left"><div class="tab_profile_value"><%= f.text_field :date,  :size => 18 %></div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header"><%= f.label :waist %></div></td>
			<td align="left"><div class="tab_profile_value"><%= f.text_field :waist, :size => 5%>cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header"><%= f.label :neck %></div></td>
			<td align="left"><div class="tab_profile_value"><%= f.text_field :neck, :size => 5%>cm</div></td>
		</tr>
			<tr>
				<td><div class="tab_profile_header"><%= f.label :hip %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :hip, :size => 5%>cm</div></td>
			</tr>
						<tr>
				<td><div class="tab_profile_header"><%= f.label :left_arm %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :left_arm, :size => 5%>cm</div></td>
			</tr>
						<tr>
				<td><div class="tab_profile_header"><%= f.label :right_arm %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :right_arm, :size => 5%>cm</div></td>
			</tr>
						<tr>
				<td><div class="tab_profile_header"><%= f.label :left_leg %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :left_leg, :size => 5%>cm</div></td>
			</tr>
						<tr>
				<td><div class="tab_profile_header"><%= f.label :right_leg %></div></td>
				<td align="left"><div class="tab_profile_value"><%= f.text_field :right_leg, :size => 5%>cm</div></td>
			</tr>
		<tr>
			<td align="center" colspan="2"><div class="tab_profile_value"><%= f.submit %></div></td>
		</tr>
	</table>
<% end %>

</body>
</html>

app/views/weights/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
						"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
	<title>MyWeight - Show Weight</title>
	<%= stylesheet_link_tag "myweight", :media => "all" %>
</head> 
<body id="store">
<h2>Show Weight</h2>
<p>Go to <%= link_to "weights", home_index_path%>.</p>
	<table>
		<tr>
			<td><div class="tab_profile_header">Weight</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.weight %> kgs</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Date</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.date.strftime("%d/%m/%Y %H:%M")%></div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Waist</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.waist %> cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Neck</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.neck%> cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Height</div></td>
			<td align="left"><div class="tab_profile_value"><%=current_user.height%> cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Hip</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.hip%>cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Left Arm</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.left_arm%>cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Right Arm</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.right_arm%>cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Left Leg</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.left_leg%>cm</div></td>
		</tr>
		<tr>
			<td><div class="tab_profile_header">Right Leg</div></td>
			<td align="left"><div class="tab_profile_value"><%=@weight.right_leg%>cm</div></td>
		</tr>
	</table>
</body>
</html>